name: Python CI
on: 
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Project Dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest -x -vv
