# Generated by Django 4.2 on 2023-04-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('movie_review', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='movie_review.country',
            ),
            preserve_default=False,
        ),
    ]
